# Set the server name to suppress warnings
ServerName localhost

# File serving location
Alias /nuotti_files /mnt/nuotti_files

# Enable debug logging
LogLevel debug wsgi:debug

<Directory /mnt/nuotti_files>
    Options -Indexes
    AllowOverride None

    # Enable basic authentication
    AuthType Basic
    AuthName "Token Required"
    AuthBasicProvider wsgi
    WSGIAuthUserScript /mnt/fileserver-app/nuottiserver_files_auth.py
    
    # First check file types
    <FilesMatch "\.(pdf|jpg|jpeg|png|gif)$">
        Require valid-user
    </FilesMatch>
    <FilesMatch "^(?!.*\.(pdf|jpg|jpeg|png|gif)$).*$">
        Require all denied
    </FilesMatch>
</Directory> 